### ISSUE TITLE
triggerEvent issue IE 11

### ISSUE THREAD

**Issue by santanapaulo** [emberjs/ember-test-helpers#405]
Hi there. I have been testing my application on IE 11, and maybe I found an interesting "bug". When I wrote a test that triggers an event blur, it worked very fine on Google Chrome, but it does not on IE 11. The test executes the triggerEvent function, but the action is not really executed.

This is how the test is implemented: ![capturar4](https://user-images.githubusercontent.com/15819810/43972510-fed1a44a-9caa-11e8-85a0-29e04a1ac926.PNG)

This step gets an "ok", but the field is still focused. Which means that the action that is supposed to be fired, it's not.

**Comment by rwjblue** [comment]
FWIW, We have a custom `blur()` helper that we have implemented, and its tests _do_ pass on IE11.

**Comment by santanapaulo** [comment]
@rwjblue is there any documentation where I can read about it?

**Comment by rwjblue** [comment]
Yep! The API docs are linked to from the README.

https://github.com/emberjs/ember-test-helpers/blob/master/API.md#blur

**Comment by santanapaulo** [comment]
I am still getting an error. I had tried triggerEvent('element', blur|focusout|) and the blur function, and still not works. The IE 11 seems not fire the event during tests.
